version: '3'
services:
  tests_py311:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.11
    command: nox --non-interactive -s tests


  tests_py312:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.12
    command: nox --non-interactive -s tests


  tests_py313:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.13
    command: nox --non-interactive -s tests
